### ISSUE TITLE
Native add-on for Firefox

### ISSUE THREAD

**Issue by indeyets** [bengrosser/twitter-demetricator#1]
Firefox uses chrome-compatible add-ons for quite some time now. Does demetricator use any chrome-specific APIs which prevent porting?

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension

**Comment by bengrosser** [comment]
Hmm, will look into it this weekend and get back to you. 

Last time I tried to do a Firefox extension is was a waste of time because my submission sat in a review queue for weeks with no action before I gave up. But I've heard it's improved now.

**Comment by bengrosser** [comment]
@indeyets [Here it is](https://addons.mozilla.org/en-US/firefox/addon/twitter-demetricator/). Had a few things to adjust, but it wasn't too bad. Give it a try for me? All appears ok as far as I can tell, but I mostly live in Chrome.

**Comment by sknebel** [comment]
appears to work just as it should! 👍

**Comment by bengrosser** [comment]
Great, thanks for the nudge. I found one bug I still have to fix on FF version. Will upload tonight. If you find any others, let me know.
