### ISSUE TITLE
Selectively allowing metrics through on Chrome

### ISSUE THREAD

**Issue by dshemetov** [bengrosser/twitter-demetricator#16]
Was working fine for most of October on Chrome, until recent weeks, something appears to have let metrics through on: profile page and on the page for a specific tweet. Feed and replies are still hidden though.

**Comment by dshemetov** [comment]
This is on new Twitter, regular twitter.com. Any hints on where follower stats on profiles / tweets get parsed in [this](https://github.com/bengrosser/twitter-demetricator/blob/master/chrome/td.user.js)?

**Comment by bengrosser** [comment]
thanks for reaching out. scheduled for release 1.2.0 this weekend (I have the fix already in place, but won't close this until it's released)

**Comment by dshemetov** [comment]
Awesome! Thanks for doing this, btw @bengrosser!

**Comment by bengrosser** [comment]
fixed, released (firefox is out, still waiting on chrome review but should be out soon)
