### ISSUE TITLE
Demetricator hides the dates

### ISSUE THREAD

**Issue by sejka** [bengrosser/twitter-demetricator#2]
https://i.imgur.com/fuaM4V5.gifv

Demetricator hides the dates of tweets (1d, 23h etc.). Suprisingly it can leave it for older tweets (Feb 12). Is that correct behaviour?

**Comment by gadenbuie** [comment]
This is intended behavior and is described in the [FAQ](https://bengrosser.com/projects/twitter-demetricator/faq-for-twitter-demetricator/):

> Q: What happened to the times on each tweet?
>
> A: Relative age counts, such as 37m, 2h, or, on TweetDeck, 4d, are metrics. Therefore, they are removed. Timestamps such as 3:43am – 21 Feb 2018 are left intact.

**Comment by sejka** [comment]
thanks a bunch!

**Comment by aaronbauman** [comment]
Love this extension, but i already miss the dates.
Any chance you'd consider exposing an option to either of these features?
- convert relative ages to timestamps
- disable this feature and show all dates, including relative ages

**Comment by bengrosser** [comment]
@aaronbauman -- curious, now that you've had it a few days (if still using it), are you still missing the age metrics?

I am open to the idea of converting relative ages to timestamps. As is probably obvious, I am reluctant to unhide age metrics (my research has shown they are as much as if not more so prescriptive of user (re)action as like/follower/etc counts).

**Comment by aaronbauman** [comment]
Was jarring at first, but now I'm not really missing it.
Thanks for the followup!

**Comment by bengrosser** [comment]
Thanks @aaronbauman, that's helpful to hear!

I will also think about / investigate conversion of relative age metrics back into timestamps as an option, as such a move might ease the jarring transition.
