### ISSUE TITLE
Display date

### ISSUE THREAD

**Issue by AXiSource** [bengrosser/twitter-demetricator#5]
Can you help me remove the opacity of the date please ?
(I created a new issue in case somebody else looks for this option)

Thanks for this plug-in.

**Comment by bengrosser** [comment]
Only age metrics are hidden, not dates/timestamps. So, 5m gets hidden but 5:05pm 8/29/20 doesn't. will leave this open in case it gets more votes.

**Comment by bengrosser** [comment]
I decided to add an option for this. Version 1.3.0.
