### ISSUE TITLE
Cannot install in ViolentMonkey: Invalid Script

### ISSUE THREAD

**Issue by kowith337** [bengrosser/twitter-demetricator#6]
### Produced on
**Browser**:
1. Edge Dev 79.0.301.2
2. Slimjet 24.0.5.0 (based on Chromium 76.0.3809.87)

**Extension**: ViolentMonkey 2.11.2 (Chrome Web Store)

![image](https://user-images.githubusercontent.com/16535467/67303308-7b6ad880-f51c-11e9-81a0-0201812876aa.png)
![image](https://user-images.githubusercontent.com/16535467/67303961-5cb91180-f51d-11e9-89e3-8d58ff095379.png)

**Comment by bengrosser** [comment]
Thanks for this. I haven't done much testing with Edge and have never used ViolentMonkey. Do you get the same results with Tampermonkey on Edge?

**Comment by kowith337** [comment]
I didn't install TamperMonkey yet (and may selfie reason for prefer not to...), but because this is the new Edge Chromium, I think all of Chrome extensions are compatible to use.

Update edit: with quick test, the installation doesn't have problem for TamperMonkey.
