### ISSUE TITLE
Dot shows next to comment / like / retweet icons on every tweet, even when there are none.

### ISSUE THREAD

**Issue by darkpivot** [bengrosser/twitter-demetricator#8]
This seems to have happened very recently, but every tweet now shows an indicator dot next to the comment, like or retweet icons even when there aren't any on that post.

**Comment by bengrosser** [comment]
Thanks for letting me know! I will fix this as soon as I can! Should be a quick fix.

**Comment by bengrosser** [comment]
fixed, released (firefox is out, still waiting on chrome review but should be out soon). also, redid the dots so they are a lot less wonky now
